SELECT * from customer limit 20

-- Revinue generated by male vs female

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- customer used discount but still paid more than average amount

select  customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- top 5 products with heighest review ratings

select item_purchased, round(AVG(review_rating::numeric),2) as "Average Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- average purchase amount between Standard Express and Express Shipping

select shipping_type, 
round(AVG(purchase_amount),2) as "Average Amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- average spend and total revenue generated by subscribers and non-subscribers

select subscription_status, 
count(customer_id) as total_customer,
round(AVG(purchase_amount),2) as average_purchase,
round(sum(purchase_amount),2) as revinue_generated
from customer
group by subscription_status
order by average_purchase, revinue_generated desc;

-- top 5 products having heighest percentage of purchases with discount applied

select item_purchased,
round(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Customer segregation into New, Returning, Loyal based on thier total previous purchases
with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer
)

select customer_segment, count(*) AS "Number of Customers"
from customer_type
group by customer_segment
;

-- top 3 most purchased products within each category

with item_counts as (
select item_purchased,
category,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
;