SELECT * from customer limit 20

-- Revinue generated by male vs female

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- customer used discount but still paid more than average amount

select  customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- top 5 products with heighest review ratings

select item_purchased, round(AVG(review_rating::numeric),2) as "Average Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- average purchase amount between Standard Express and Express Shipping

select shipping_type, 
round(AVG(purchase_amount),2) as "Average Amount"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- average spend and total revenue generated by subscribers and non-subscribers

select subscription_status, 
count(customer_id) as total_customer,
round(AVG(purchase_amount),2) as average_purchase,
round(sum(purchase_amount),2) as revinue_generated
from customer
group by subscription_status
order by average_purchase, revinue_generated desc;

-- top 5 products having heighest percentage of purchases with discount applied

select item_purchased,
round(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Customer segregation into New, Returning, Loyal based on thier total previous purchases
with customer_type as(
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer
)

select customer_segment, count(*) AS "Number of Customers"
from customer_type
group by customer_segment
;

-- top 3 most purchased products within each category

with item_counts as (
select item_purchased,
category,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3
;


-- SEASONAL ANALYSIS

-- Total revenue, orders, and avg order value by season
SELECT season,
       COUNT(*) AS total_orders,
       ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_order_value
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;

-- Best performing category within each season
WITH season_category AS (
    SELECT season, category,
           SUM(purchase_amount) AS revenue,
           RANK() OVER(PARTITION BY season ORDER BY SUM(purchase_amount) DESC) AS rnk
    FROM customer
    GROUP BY season, category
)
SELECT season, category, ROUND(revenue::numeric, 2) AS revenue
FROM season_category
WHERE rnk = 1
ORDER BY season;

-- Revenue and order count by age group

WITH categorized_customers AS (
    SELECT 
        *,
        CASE 
            WHEN age BETWEEN 18 AND 31 THEN 'Young Adult (18-31)'
            WHEN age BETWEEN 32 AND 44 THEN 'Adult (32-44)'
            WHEN age BETWEEN 45 AND 57 THEN 'Middle-Age (45-57)'
            ELSE 'Senior (58-70)'
        END AS age_category  -- Changed from 'age_group'
    FROM customer
)
SELECT 
    age_category, -- Update this reference
    COUNT(*) AS total_customers,
    ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_order_value
FROM categorized_customers
GROUP BY age_category -- Update this reference
ORDER BY avg_order_value DESC;

-- Most popular category per age group

WITH age_cat AS (
    SELECT 
        CASE 
            WHEN age BETWEEN 18 AND 31 THEN 'Young Adult'
            WHEN age BETWEEN 32 AND 44 THEN 'Adult'
            WHEN age BETWEEN 45 AND 57 THEN 'Middle-Age'
            ELSE 'Senior' 
        END AS age_group,
        category,
        COUNT(*) AS purchases,
        RANK() OVER(
            PARTITION BY CASE 
                WHEN age BETWEEN 18 AND 31 THEN 'Young Adult'
                WHEN age BETWEEN 32 AND 44 THEN 'Adult'
                WHEN age BETWEEN 45 AND 57 THEN 'Middle-Age'
                ELSE 'Senior' 
            END 
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer
    GROUP BY 1, category 
)
SELECT age_group, category, purchases
FROM age_cat
WHERE rnk = 1
ORDER BY age_group;

-- Payment method revenue and average spend
SELECT payment_method,
       COUNT(*) AS total_transactions,
       ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER(), 2) AS pct_of_total
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Shipping type preference by subscription status

SELECT subscription_status, shipping_type,
       COUNT(*) AS orders,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM customer
GROUP BY subscription_status, shipping_type
ORDER BY subscription_status, orders DESC;

-- Customers who prefer express shipping AND have >5 previous purchases

SELECT customer_id, age, gender, previous_purchases,
       shipping_type, purchase_amount
FROM customer
WHERE shipping_type = 'Express'
  AND previous_purchases > 5
ORDER BY previous_purchases DESC, purchase_amount DESC
LIMIT 20;

-- High-value customer identification (spend > 90th percentile)
WITH percentile AS (
    SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY purchase_amount) AS p90
    FROM customer
)
SELECT c.customer_id, c.age, c.gender, c.category,
       c.purchase_amount, c.previous_purchases, c.subscription_status
FROM customer c, percentile p
WHERE c.purchase_amount >= p.p90
ORDER BY c.purchase_amount DESC;


-- Correlation between previous purchases and spend category
SELECT
    CASE
        WHEN previous_purchases = 1       THEN 'New (1)'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning (2-10)'
        ELSE 'Loyal (10+)'
    END AS customer_type,
    COUNT(*) AS customers,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
    ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_rating
FROM customer
GROUP BY customer_type
ORDER BY avg_spend DESC;


-- Gender × Category revenue matrix
SELECT gender, category,
       COUNT(*) AS orders,
       ROUND(SUM(purchase_amount)::numeric, 2) AS revenue,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM customer
GROUP BY gender, category
ORDER BY gender, revenue DESC;


-- Month-over-month equivalent — purchase frequency analysis
SELECT frequency_of_purchases,
       COUNT(*) AS customers,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
       ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue
FROM customer
GROUP BY frequency_of_purchases
ORDER BY avg_spend DESC;


-- Rolling revenue contribution — cumulative % by category
WITH cat_rev AS (
    SELECT category,
           ROUND(SUM(purchase_amount)::numeric, 2) AS revenue
    FROM customer
    GROUP BY category
),
ranked AS (
    SELECT category, revenue,
           ROUND(100.0 * revenue / SUM(revenue) OVER(), 2) AS pct,
           ROUND(100.0 * SUM(revenue) OVER(ORDER BY revenue DESC) / SUM(revenue) OVER(), 2) AS cumulative_pct
    FROM cat_rev
)
SELECT category, revenue, pct AS pct_of_total, cumulative_pct
FROM ranked
ORDER BY revenue DESC;

-- Customers with above-average spend in EVERY category they bought from
-- Modified Q24: Customers above avg in at least 2 categories

WITH category_avgs AS (
    SELECT category,
           ROUND(AVG(purchase_amount)::numeric, 2) AS category_avg
    FROM customer
    GROUP BY category
)
SELECT c.customer_id, c.age, c.gender,
       c.category, c.purchase_amount,
       ca.category_avg,
       ROUND(c.purchase_amount - ca.category_avg, 2) AS above_avg_by
FROM customer c
JOIN category_avgs ca ON c.category = ca.category
WHERE c.purchase_amount >= ca.category_avg
ORDER BY above_avg_by DESC
LIMIT 20;

-- Subscription conversion opportunity — non-subscribers with loyal behaviour
SELECT customer_id, age, gender, previous_purchases,
       frequency_of_purchases, purchase_amount,
       ROUND(AVG(purchase_amount) OVER()::numeric, 2) AS overall_avg
FROM customer
WHERE subscription_status = 'No'
  AND previous_purchases > 10
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY previous_purchases DESC, purchase_amount DESC
LIMIT 25;


